<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Full Name' => 'الاسم باكامل',
    'Select What Do you want to do' => 'اختر ماذا تريد ان تفعل',
    '911 Restaurants' => 'مطاعم 911',
    'Feedback System' => 'برنامج التغذية الراجعة',
    'Softwares' => 'البرمجيات',
    'Start Software' => 'ابداء البرنامج',
    'feedback details' => 'برنامج يتيح للزبائن بالقيام على التقيم و ترك تغذية راجعة للمنظمة لبقاء الاداء على اكمل و احسن وجه ممكن و اضافة التطورات و مواكبة افضل الخدمات',
    'Please select a branch to start feedback system' => 'يرجى اختيار الفرع ليدء برنامج التغذية الراجعة',
    'Please Select Branch' => 'يرجى اختيار الفرع',
    'POOR' => 'ضعيف',
    'AVERAGE' => 'متوسط',
    'GOOD' => 'جيد',
    'EXCELLENT' => 'ممتاز',
    'How do you rate our services ?' => 'كيف تقيم الخدمات التي قمنا بها ؟',
    'Email' => 'البريد الالكتروني',
    'Phone Number' => 'رقم الهاتف',
    'Note\Message' => 'ملاحظة\رسالة',
    'Submit form' => 'ارسال النموذج',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
];
